name: pullimages
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
            docker login --username=${{ secrets.USR }} --password=${{ secrets.PSW }} registry.cn-shenzhen.aliyuncs.com
            docker pull registry.k8s.io/ingress-nginx/controller:v1.8.1@sha256:e5c4824e7375fcf2a393e1c03c293b69759af37a9ca6abdb91b13d78a93da8bd
            docker pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b
            docker tag registry.k8s.io/ingress-nginx/controller:v1.8.1@sha256:e5c4824e7375fcf2a393e1c03c293b69759af37a9ca6abdb91b13d78a93da8bd registry.cn-shenzhen.aliyuncs.com/czjhlsj/registry_k8s_io:ingress-nginx-controller-v1.8.1
            docker push registry.cn-shenzhen.aliyuncs.com/czjhlsj/registry_k8s_io:ingress-nginx-controller-v1.8.1
            docker tag registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b registry.cn-shenzhen.aliyuncs.com/czjhlsj/registry_k8s_io:ingress-nginx-kube-webhook-certgen-v20230407
            docker push registry.cn-shenzhen.aliyuncs.com/czjhlsj/registry_k8s_io:ingress-nginx-kube-webhook-certgen-v20230407
