# This is a basic workflow to help you get started with Actions

name: pullimages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
            docker login --username=${{ secrets.USR }} --password=${{ secrets.PSW }} registry.cn-shenzhen.aliyuncs.com
            docker pull registry.k8s.io/ingress-nginx/controller:v1.8.1@sha256:e5c4824e7375fcf2a393e1c03c293b69759af37a9ca6abdb91b13d78a93da8bd
            docker pull registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b
            docker tag registry.k8s.io/ingress-nginx/controller:v1.8.1@sha256:e5c4824e7375fcf2a393e1c03c293b69759af37a9ca6abdb91b13d78a93da8bd registry.cn-shenzhen.aliyuncs.com/czjhlsj/registry_k8s_io:ingress-nginx-controller-v1.8.1
            docker push registry.cn-shenzhen.aliyuncs.com/czjhlsj/registry_k8s_io:ingress-nginx-controller-v1.8.1
            docker tag registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b registry.cn-shenzhen.aliyuncs.com/czjhlsj/registry_k8s_io:ingress-nginx-kube-webhook-certgen-v20230407
            docker push registry.cn-shenzhen.aliyuncs.com/czjhlsj/registry_k8s_io:ingress-nginx-kube-webhook-certgen-v20230407
